### ISSUE TITLE
Downloading of raw videos faills for some video ids

### ISSUE THREAD

**Issue by noamwies** [apple/ARKitScenes#1]
Hi, do you have any idea why the following command fails on some of the video ids and succeed on others?

#### Failed
```
python download_data.py raw --split Training--video_id 40777060 --download_dir .
```
#### Succed
```
python download_data.py raw --split Validation --video_id 48458667 --download_dir .
```

Thanks, Noam

**Comment by PeterZheFu** [comment]
Thanks @noamwies for catching it. We are checking the access issues and will resolve it asap.

**Comment by PeterZheFu** [comment]
Hi @noamwies, 
    Thanks for raising this issue.
    This has been fixed. I have successfully downloaded it.
    I will close this issue. Feel free to re-open it if you find any additional issues. Thanks.

**Comment by noamwies** [comment]
Thanks for the fixing! most of the scenes works now but i still found 1 problematic scene

```bash
python3 download_data.py raw --split Validation --video_id 43896321 --download_dir .```
