### ISSUE TITLE
Question about raw Faro high-resolution XYZRGB point cloud

### ISSUE THREAD

**Issue by Gofinge** [apple/ARKitScenes#11]
Thank you for the impressive large-scale indoor dataset collecting work. It's a significant dataset with many possibilities for high-level application scenarios, and I like it.

It is thoughtful to generate ground truth high-resolution depth maps by discarding geometry which a direct line-of-sight from the novel viewpoint cannot be guaranteed. 

But I think if we can get access to raw Faro high-resolution XYZRGB point cloud, it will grant the dataset more potential, such as point cloud completion task.

Will it be possible for us to get access to much more raw data collected in your well-designed data collecting process? We can explore more meaningful settings to explore 3D understanding in such a large-scale real indoor dataset.

**Comment by afshindn** [comment]
Thanks for the note and recommendation. Unfortunately such data is not currently available with the first release of ARKitScenes partly due to storage consideration as those assets are pretty large. However, we are considering the release of the raw Faro point clouds in future and will keep you posted.

**Comment by PeterZheFu** [comment]
Closing the issue for now. Feel free to re-open it if you have further questions.

**Comment by PeterZheFu** [comment]
Re-opening the issue till fully resoolved.

**Comment by zbs881314** [comment]
When can you release the raw Faro point clouds?

**Comment by cy94** [comment]
@afshindn @PeterZheFu thanks for the comprehensive dataset! I'm interested in the Faro point clouds as well, would it be possible to provide a few samples and any other information about the scanning process, such scanner settings, resolution and scan time? This would be useful for us to evaluate on custom datasets.

**Comment by arik1089** [comment]
Hi, thanks again for the interest in our dataset! 
We recently released high resolution venue point-clouds that were produced by Faro Lidars. They are now available to download from the raw dataset by using the `--download_laser_scanner_point_cloud` flag.
Please see the [data documentation](https://github.com/apple/ARKitScenes/blob/main/DATA.md) and [raw dataset documentation](https://github.com/apple/ARKitScenes/blob/main/raw/README.md) for more information.

**Comment by Gofinge** [comment]
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/39218229/174960361-46ce8578-65fe-4c9b-9aaa-667bbf384bea.png">
Hi, really thanks for valuing our request. I was trying to download a high-resolution venue by following the example script in the image shown above. And It seems that "Laser scanner point clouds for video 41048190 are not available" and the video id is provided by docs.

**Comment by zbs881314** [comment]
I have  downloaded the video_id 47333462 (laser scanner point cloud),  but I found that the name of the downloaded point cloud file is different from 47333462，and its name is 467138. 
![1656466785891](https://user-images.githubusercontent.com/34663445/176332759-c0989ff8-6334-41b8-bc91-cfba130dfde9.png)

**Comment by Gofinge** [comment]
Hi, @zbs881314 :
The *laser_scanner_point_clouds_mapping.csv* in the ARKitScenes dataset home folder might solve your question. A mapping exists between video_id and visit_id.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/39218229/176338380-8bbe22e8-00de-4f6c-a089-5b4d000051c4.png">
