### ISSUE TITLE
Raw Dataset Size

### ISSUE THREAD

**Issue by bookhahn** [apple/ARKitScenes#12]
Hi,

thank you for providing this massive dataset! What is approximately the size of the raw data? Is it around 13 TB?

Thanks in advance!

**Comment by PeterZheFu** [comment]
Hi @bookhahn,
   Thanks for your question. Yep, the total size is 12.7 TiB.

**Comment by PeterZheFu** [comment]
closing the issue for now. Feel free to re-open it.
