### ISSUE TITLE
Access  to https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1 denied

### ISSUE THREAD

**Issue by kgcs** [apple/ARKitScenes#13]
I would like to download the dataset but the access  to https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1  is denied

When using the example command, e.g.

python download_data.py raw --split Training  --video_id 47334522  --download_dir raw

I get the error message 
KeyError: 'ARkitscense_url'

and if I want to access in a browser I get:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>FY8DYK2G1GDQK3YN</RequestId>
<HostId>T9z6QNoG8j1Tv7a6BG8IqEsyp+cqlx0Avgj7wKSq4kWbsCKyZZn/I3J8aP0OWdjAsu9OxP5yWI4=</HostId>
</Error>

Many thanks in advance for your help.

**Comment by PeterZheFu** [comment]
Hi @kgcs ,

    Thanks for your interest in our dataset and for reaching out. Sorry for my belated reply.
    I just tried below command on a public network (non company VPN) and it works for me. Since I cannot reproduce the error, it is a bit hard for me to debug. Can you try again or provide more info? Or, can you try downloading a 3dod scene and check if doing that works? Thanks.

Best, 
Peter

 ARKitScenes peter$ python3 download_data.py raw --split Training --video_id 47334522 --download_dir raw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  430M  100  430M    0     0  38.0M      0  0:00:11  0:00:11 --:--:-- 42.0M

**Comment by kgcs** [comment]
The problem was maybe on our side because now it seems to works. Thanks for your help. G
