### ISSUE TITLE
highres_depth in raw dataset

### ISSUE THREAD

**Issue by likojack** [apple/ARKitScenes#17]
Dear ARKitScenes developers,

Thanks for the excellent work! I am particularly interested in using high-resolution depth maps in the raw dataset. The ones in the upsampling subset are too sparse for my use case, unfortunately. 

However, after I downloaded one of the sequences in the raw dataset using the command below:
`python3 download_data.py raw --split Training --video_id 41048190 --download_dir /tmp/Datasets_ssd/`
I couldn't find `highres_depth`. Could you please advise if I missed anything? 

On a separate note, I also wonder if there are any plans to release the point clouds captured by the Faro laser scanner and how you computed the confidence for depth maps if it could be disclosed.

**Comment by amariucaitheodor** [comment]
I also could only find high-resolution depth maps in the upsampling subset.

**Comment by weders** [comment]
Hi, 

I am also looking for the high-res depth maps corresponding to the sequence provided in the raw dataset. According to [the documentation](https://github.com/apple/ARKitScenes/tree/main/raw#data-organization-and-format-of-input-data), they should be contained in the folder. Is there any plan to release this data soon? Thanks!

**Comment by arik1089** [comment]
Hi,

Thanks so much for the interest in our dataset!

Referring to your three questions:
1. The lack of the highres_depth asset in the raw dataset - the data exists for all upsampling dataset videos, while non-Upsampling videos will not have this data available. The download script will be adapted to enable the download of this asset when available from the raw dataset
2. Faro laser scanner RGBD point clouds - We are working on it, hoping to release the data in the coming weeks
3. The depth maps’ confidence is calculated by ARKit framework, please look here for details: https://developer.apple.com/documentation/arkit/ardepthdata/3566295-confidencemap

**Comment by yueruchen** [comment]
Hi @arik1089 ,

Thanks for sharing this great dataset. Is the high-res depth map now available for raw set? The upsampling set seems to too sparse for my purpose.

Best,

**Comment by arik1089** [comment]
Hi,

Updating on the previous issues:

1. The 10 FPS highres depth assets are now available to download from the raw dataset. For example, this will download the highres_depth assets for video id `48458713` : `python3 download_data raw --split Training --video_id 48458713 --download_dir /tmp/raw_ARKitScenes/ --raw_dataset_assets highres_depth`
2. The Faro laser scanner point clouds are now available to download from the raw dataset by using the `--download_laser_scanner_point_cloud flag`. Please see the [data documentation](https://github.com/apple/ARKitScenes/blob/main/DATA.md) and [raw dataset documentation](https://github.com/apple/ARKitScenes/blob/main/raw/README.md) for more information.

**Comment by yueruchen** [comment]
Hi @arik1089,

I got an error when using this command:
```
Error downloading https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/raw/Training/42446103/highres_depth.zip, error: Command 'curl https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/raw/Training/42446103/highres_depth.zip -o highres_depth.zip --fail' returned non-zero exit status 22.

```

**Comment by yueruchen** [comment]
Hi @arik1089 ,

Thanks for providing the 10fps highres depth! Would you mind providing the code about how you rendered the depth from the mesh file? Thant would help a lot.

Best,
