### ISSUE TITLE
gt depth and gt color

### ISSUE THREAD

**Issue by jeannotes** [apple/ARKitScenes#19]
hi, I download upsampling data, there are 4 types assets, confidence, lowres_depth, highres_depth and wide.
Q1: is the highres_depth corresponding to wide_rgb,
Q2: is the 'lowres_depth' captured by iphone and meanwhile corresponding to wide?

**Comment by arik1089** [comment]
Hi, thanks for the questions and your interest in our dataset. 

To answer your questions: 
1. Yes, each 'highres_depth' image corresponds to a 'wide_rgb' image with the same timestamp
2. Yes, the 'lowres_depth' image was captured with an iOS device using ARKit’s sceneDepth API. Each 'lowres_depth' image also corresponds to 'highres_depth' and  'wide_rgb' images with the same timestamp

**Comment by arik1089** [comment]
Closing the issue for now, feel free to re-open it.
