### ISSUE TITLE
Downloading of mesh files

### ISSUE THREAD

**Issue by noamwies** [apple/ARKitScenes#2]
Hi, when i try to download mesh files

```bash
python3 download_data.py raw --split Validation --video_id 48458667 --download_dir . --raw_dataset_assets mesh
```

i always got errors like that
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>S35X8MRZXWAHDNCD</RequestId><HostId>RUdvpESfdl/jZ20rR9qMA67MmnhqACL1JTE6CXWbyn1qXnqby7vU6nYra1HBRIUX2ypgy2mxLfM=</HostId></Error>
```

**Comment by MemoryNode** [comment]
in download_data.py , change  "file_names.append(f'{video_id}_3dod_mesh.fly')" to "file_names.append(f'{video_id}_3dod_mesh.ply')"

**Comment by PeterZheFu** [comment]
Hi @MemoryNode,
    Thanks for raising this issue. We are working on it and will push a fix soon.
    Meanwhile, the .fly seems to be corrupted. As a temporary alternative, the same file exists in 3dod sub directory with the correct .ply mesh. Hope this is helpful~

**Comment by YuriFeigin** [comment]
Hey @noamwies 
Thanks for raising this issue.
We fixed the issue as suggested by @MemoryNode 
I will close this issue. Feel free to re-open it if you find any additional issues. Thanks.
