### ISSUE TITLE
When can you release the raw Faro high-resolution XYZRGB point cloud

### ISSUE THREAD

**Issue by zbs881314** [apple/ARKitScenes#20]
I also think if we can get access to raw Faro high-resolution XYZRGB point cloud, it will grant the dataset more potential, such as point cloud completion task. Further speaking, it will also promote the promotion of Apple products.

**Comment by arik1089** [comment]
Hi, thank for the interest in our dataset! 
We recently released high resolution venue point-clouds that were produced by Faro Lidars. They are now available to download from the raw dataset by using the `--download_laser_scanner_point_cloud` flag.
Please see the [data documentation](https://github.com/apple/ARKitScenes/blob/main/DATA.md) and [raw dataset documentation](https://github.com/apple/ARKitScenes/blob/main/raw/README.md) for more information.
