### ISSUE TITLE
.ply file with original color

### ISSUE THREAD

**Issue by tmatuan-smu** [apple/ARKitScenes#21]
Hi ARKitScenes researchers,

I am new to 3D points cloud, so I don't know how to reconstruct color (from the original scene) to .ply mesh. Can you please help to give some instructions. I would like to load the .ply file into Unity 3D for my research project.

Thanks,

**Comment by PeterZheFu** [comment]
Hi @tmatuan-smu ,
   Thanks for your question. The video_id_3dod_mesh.ply mesh are already colored. For example, you can use the software MeshLab to open it.

**Comment by arik1089** [comment]
Closing this issue for now. Please feel free to re-open in case you have further questions.
