### ISSUE TITLE
Camera pose alignment

### ISSUE THREAD

**Issue by yueruchen** [apple/ARKitScenes#26]
Hi,

Thanks for releasing this dataset. Since the highres depth map is too sparse to me, I'm trying to re-rendering highres depth map using the given camera parameters and mesh. I suppose the '.traj' contains extrsincs of each frames. Just wondering what is the orientation of raotation and translation, does that represent x,y,z or other coordinate system? which axis face the front of the camera? What is the near and far distance of each depth map?

Best,

**Comment by PeterZheFu** [comment]
Hi @yueruchen,
     Thanks for your question.
      For camera poses, you can refer to the documentation here https://github.com/apple/ARKitScenes/blob/main/DATA.md#dataset-files-formats which is

> .traj - is a space-delimited file where each line represents a camera position at a particular timestamp.
> Column 1: timestamp
> Columns 2-4: rotation (axis-angle representation in radians)
> Columns 5-7: translation (in meters)

Also, you can visualize the axis (axes) using the script here 

> cd ./threedod/benchmark_scripts
> python show_3d_bbox_annotation.py \
>        -f /tmp/raw_ARKitScenes/3dod/Training/41254925/41254925_3dod_mesh.ply \
>        -a /tmp/raw_ARKitScenes/3dod/Training/41254925/41254925_3dod_annotation.json

**Comment by yueruchen** [comment]
Hi @PeterZheFu ,

Thanks so much for replying!!

I tried to plot camera trajectory over mesh and see if that curve match the observation. I did it by treating translation values as x, y, z respectively. Here is what I got in `Validation/42446103` (I use `Raw` set and `.traj` file): 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/14892792/174665245-62dff2da-2ded-4a87-8f9f-1db46bc7db40.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/14892792/174665263-c0a6757b-b958-479a-8801-3ba007b72566.png">

The plot curve seems very weird. To further debug the issue, I try to check the `.traj` file (uploaded [here](https://drive.google.com/file/d/1V_flxEUIqivpLQpbMc56fn2ODyl5fyk5/view?usp=sharing)). And I found that, the maximum value - minimum value could be larger than 4 meters in every axis. However, seems the video stream is collected by human, the `max - min` couldn't be larger than 2 meters in `z` axis, do you have any idea about which step I've been wrong with? Thanks so much!!

**Comment by PeterZheFu** [comment]
Closing the issue for now. Feel free to re-open it if you have further questions~

**Comment by yueruchen** [comment]
Thanks!

**Comment by kylekam** [comment]
Hi, @yifanjiang19 . I'm curious as to how you were able to re-render the highres-depth map when then camera extrinsics for the highres-depth images aren't provided.

**Comment by kylekam** [comment]
Nevermind, I re-read the paper and I figured I could reuse the lowres.traj as the extrinsics. Are the highres wide intrinsics provided somewhere?
