### ISSUE TITLE
Encounter 403 Forbidden When Downloading Mesh File

### ISSUE THREAD

**Issue by Gofinge** [apple/ARKitScenes#28]
Hi, thanks for the great work again! I am trying to download the mesh file of each scan produced by ARKit (the low-resolution one). Unfortunately,  I encounter 403 forbidden when downloading these files (limit the download file list to mesh only), and I worry about data loss. The following image shows some of my logs.

![image](https://user-images.githubusercontent.com/39218229/175485913-9c54d86e-a2f7-42c7-8673-867d2dcb3942.png)

**Comment by arik1089** [comment]
Hi @Gofinge, 
Could you please share the download command you are using?

Thanks!
Arik.

**Comment by Gofinge** [comment]
Hi @arik1089 ,
Here is an example download link extarct from original download script: "curl https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/raw/Training/47333152/47333152_3dod_mesh.ply -o 47333152_3dod_mesh.ply --fail".
 
This image shows the log produced by the original download python script.
![20761656258376_ pic](https://user-images.githubusercontent.com/39218229/175822484-cf3d82bf-e8fa-4583-906e-53555c7820ea.jpg)

This image is the error output of the *curl* order backend of the python download script.
![image](https://user-images.githubusercontent.com/39218229/175822497-c8d694b0-5e96-45d3-b5d9-5f9bdddeac09.png)

**Comment by arik1089** [comment]
This issue should be fixed in the recent update to the `download_data.py` script. 
Closing the issue for now. Please feel free to re-open if the problem re-occurs.

**Comment by mrsempress** [comment]
Hi, @arik1089 . I got the same problem recently when downloading the 3dod.
![WeChat Work Screenshot_20240105201221](https://github.com/apple/ARKitScenes/assets/31315255/61d2e2d7-50c6-4287-8e1e-f7eab4f50d5e)

**Comment by vitruvi** [comment]
I can also confirm that some videos do give 403 error and others download without problems. For instance, at the moment
https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/threedod/Training/42446156.zip gives 403 error.

Does the server deny the access of a file if it is recently reached from an IP?
