### ISSUE TITLE
semantic information tags

### ISSUE THREAD

**Issue by presunshine** [apple/ARKitScenes#3]

**Comment by presunshine** [comment]
Wow,so great!！

provide timely help to me 

I want to know if it will provide semantic information tags?

**Comment by PeterZheFu** [comment]
Hi @presunshine, 
    Thanks for your question. I am afraid that we do not provide semantic segmentation for the per frame images. 
    That being said, (maybe I am stating the obvious here) one solution can be to use a 3rd party off the shelf semantic tool to get that. Let me know if this answers your question~

**Comment by PeterZheFu** [comment]
Closing it for now. Feel free to re-open if you have additional questions.

**Comment by jeannotes** [comment]
if we do 3d to 2d project, can we get semantic information? @PeterZheFu @presunshine
