### ISSUE TITLE
About the camera extrinsics of provided highres depth map

### ISSUE THREAD

**Issue by yifanjiang19** [apple/ARKitScenes#30]
Hi,

Thanks for providing the highres depth map! That is really useful. However, I found some problems regarding to the timestamp.

For each highres depth map, I can't find the corresponding camera extrinsics in `.traj` file. For example, in `Validation/42446103`, highres depth map folder contains `42446103_78067.167.png`, but `42446103_78067.167` didn't appear in `.traj` file. I can only find extrinsics for `78067.183` and `78067.083`.

Best,

**Comment by OasisYang** [comment]
Same problem

**Comment by ManooshSamiei** [comment]
Same issue here

**Comment by PeterZheFu** [comment]
Thanks for your interest in our dataset. However, as described in the paper associated with this dataset, the highres depth maps are used for the upsampling task. For this upsampling task we release paired lowres and highres depth maps, which do not include camera extrinsics for the upsampling task. Therefore we do not have camera traj files with exact timestamps. That being said, for 3dod task we release the lowres depth frames which match the timestamps of the .traj file. Hope this information is helpful. Please feel free to let me know if you have any questions.

**Comment by PeterZheFu** [comment]
Closing the issue for now. Feel free to re-open it if you have any questions.
