### ISSUE TITLE
About lowres_wide.traj for ultra and vga images

### ISSUE THREAD

**Issue by linzhenyuyuchen** [apple/ARKitScenes#32]
Hello,
  Thank you for your sharing!
  Could you please provide some details about this dataset, such as :
  1. Whether the `lowres_wide.traj`  can be used as the extrinsic of the images in `vga_wide` and `ultra_wide` dictionary...
  2. The total size of `raw`  data using the script  [download_data.py](https://github.com/apple/ARKitScenes/blob/b8638b942f1d2c282de03dec7c9e5bf9785aad01/download_data.py), it seemed over 7TB...

**Comment by PeterZheFu** [comment]
Hi @linzhenyuyuchen , thanks for your questions.
1. Yes, it can be used for the images
2. Unfortunately, it is expected that the raw folder is quite large. One possible way is to download a small subset of it for exploration.
