### ISSUE TITLE
No raw assets given for video id xxxxxxx

### ISSUE THREAD

**Issue by choyingw** [apple/ARKitScenes#36]
Hi I tried to download the raw dataset. The command is 

python download_data.py raw --split Training --video_id_csv raw/raw_train_val_splits.csv --download_dir .

but it only shows "Warning: No raw assets given for video id xxxxxxxx" for all ids in the csv file.

**Comment by SebastianEger** [comment]
You need to define which assets you want to download with **--raw_dataset_assets**

**Comment by arik1089** [comment]
Thanks @SebastianEger for your helpful response.

@choyingw - Please download the latest version of the download script, there was a change of behavior that will download all the assets by default, if no `--raw_dataset_assets` are given. 

Closing the issue for now, feel free to re-open if you have more questions.
