### ISSUE TITLE
 Downloading of raw videos failed for some video ids

### ISSUE THREAD

**Issue by noamwies** [apple/ARKitScenes#4]
Thanks for the fixing! most of the scenes works now but i still found 1 problematic scene

```bash
python3 download_data.py raw --split Validation --video_id 43896321 --download_dir .
```

_Originally posted by @noamwies in https://github.com/apple/ARKitScenes/issues/1#issuecomment-991843788_

**Comment by noamwies** [comment]
In this scene i got the following responses

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F0VBNECTKKQEBBQ8</RequestId><HostId>O3VVbsoWoRZ3zhPiKkbaRNBxjmF7xC8YKlNV9VVPQ/eoxNdROrqXWZX+NtdAtzHT7ENOSzQQLek=</HostId></Error>
```

**Comment by YuriFeigin** [comment]
Hey @noamwies
Thanks for raising this issue.
There was a mistake in the split of this video id, the CSV file was updated with the correct split.
Other than that we updated the file to include more videos that were added to the raw dataset.
I will close this issue. Please feel free to re-open it if you find any additional issues.
Thanks.
