### ISSUE TITLE
Problems with annotation-files

### ISSUE THREAD

**Issue by M-G-A** [apple/ARKitScenes#42]
**Since I found missing objects in the object annotation files, I suggest to start a thread were we collect such issues**

In the sets 40776203 and 40776204 (Training) the bed in the corner is not labeled. It has the following transformation:
- in 40776203: center=[ 3.087, -1.471, -1.220 ], dimension=[ 2.320, 1.680, 0.461], rot=[-0.527, 0, 0]
- in 40776204: center=[ 0.585, -1.064, -1.141 ], dimension=[ 2.320, 1.680, 0.461], rot=[ 1.043, 0, 0]
![bed_missing](https://user-images.githubusercontent.com/769780/190390463-4e8ead70-b503-4413-a58b-4819a7eaa430.png)
![bed_included](https://user-images.githubusercontent.com/769780/190390481-1cef7411-8f5f-49ef-b1d8-6e4d50cc11c5.png)

**Comment by M-G-A** [comment]
Found another issue in scene 42897846 (Training):
- the file does not contain any objects, since it is an empty room. However the dict has a length =! 0. This means, that the data loader outputs an error in the 'extract_gt' function. 
In this function only the edge case of an empty annotation file is considered, hence at the end a concatenation of an empty array is executed (which is not allowed)
- the solution is to either use another function than 'np.concatenate' (i.e np.array() with .T) or check additionally for the condition 
`if len(gt) == 0:` => `if (len(gt) == 0) or (len(gt['data'])==0):` 
(there won't be any key-errors for empty dicts, since the second condition only get's checked, if the first condition does not hold)

**Comment by PeterZheFu** [comment]
Hi @M-G-A,
    Sorry for my belated reply and thanks again for raising the issue. Even though our labeling instruction does not treat mattress(es) as bed(s), we acknowledge that such definitions can be subjective. Given the fact that the GT labels have been released and may have been used in other researchers’ evaluations, it will not be easy to modify the GT labels, i.e. adding a new GT box for the mattress/bed. Hope this sounds reasonable to you and please feel free to let me know if you any further questions.
