### ISSUE TITLE
Watertight textured mesh

### ISSUE THREAD

**Issue by imbinwang** [apple/ARKitScenes#45]
Hi,

Thank you for sharing the dataset. In section 3.2 of the paper, you have metioned that watertight textured mesh could be generated by stereographic projection. Cloud you share these meshes or related code please?

**Comment by dgriffiths3** [comment]
Hi @imbinwang sorry for delayed response. These were internal assets used for generating the ground truth pose and are not part of the ARKitScenes dataset.
