### ISSUE TITLE
RAW download links are broken?

### ISSUE THREAD

**Issue by lsongx** [apple/ARKitScenes#48]
Thank you for providing a well-maintained dataset! And the super helpful APIs.

I got `Warning: No raw assets given for video id` for all RAW downloads.

**Comment by reynoldscem** [comment]
I've also found this

**Comment by PeterZheFu** [comment]
Thanks for the heads-up and thanks for your interest in our dataset. Let me check and get back to you.

**Comment by reynoldscem** [comment]
Thanks @PeterZheFu

**Comment by DuinoDu** [comment]
Any update?

**Comment by PeterZheFu** [comment]
Hi @DuinoDu ,
     Sorry for my belated reply. I have tested it the link and it works for me. In order to trouble shoot further, may I ask what is the error message you have when you run below command? Thanks.
```
python3 download_data.py raw --split Training --video_id 47333462 \
--download_dir /tmp/ARKitScenes_outside/ --download_laser_scanner_point_cloud
```

**Comment by DuinoDu** [comment]
@PeterZheFu 
Your command also works for me. But when I ran below:

```
python3 download_data.py raw --split Training --video_id_csv raw/raw_train_val_splits.csv  --download_dir /tmp/ARKitScenes_outside/
```
use `--video_id_csv` instead of `--video_id`, I met error below:

```                                                           
Warning: No raw assets given for video id 40753679                             
Warning: No raw assets given for video id 40753686                             
Warning: No raw assets given for video id 40776203                             
Warning: No raw assets given for video id 40776204                             
...
```

**Comment by AshkanGanj** [comment]
I am having the same problem downloading the raw dataset. If you could help, I would appreciate it. 
Thanks for publishing the dataset publicly.
```
https://github.com/apple/ARKitScenes/issues/48
```
Error: 
![image](https://user-images.githubusercontent.com/55941654/219219997-548074e4-96ce-410c-a4e0-a5412428ae11.png)

**Comment by PeterZheFu** [comment]
Hi all,
    Thanks for highlighting this issue. I have submitted a PR for it. Meanwhile, please kindly note that for raw data, you will need to specify the type(s) of data you would like to download.

The choices are 
```
mov annotation mesh confidence highres_depth lowres_depth lowres_wide.traj lowres_wide lowres_wide_intrinsics ultrawide 
ultrawide_intrinsics vga_wide vga_wide_intrinsics
```

for example
```shell script
python3 download_data.py raw --video_id_csv raw/raw_train_val_splits.csv --download_dir /tmp/ar_raw_all/ \
--raw_dataset_assets mov annotation mesh confidence highres_depth lowres_depth lowres_wide.traj \
lowres_wide lowres_wide_intrinsics ultrawide ultrawide_intrinsics vga_wide vga_wide_intrinsics
```

**Comment by AshkanGanj** [comment]
> Hi all, Thanks for highlighting this issue. I have submitted a PR for it. Meanwhile, please kindly note that for raw data, you will need to specify the type(s) of data you would like to download.
> 
> The choices are
> 
> ```
> mov annotation mesh confidence highres_depth lowres_depth lowres_wide.traj lowres_wide lowres_wide_intrinsics ultrawide 
> ultrawide_intrinsics vga_wide vga_wide_intrinsics
> ```
> 
> for example
> 
> ```shell
> python3 download_data.py raw --video_id_csv raw/raw_train_val_splits.csv --download_dir /tmp/ar_raw_all/ \
> --raw_dataset_assets mov annotation mesh confidence highres_depth lowres_depth lowres_wide.traj \
> lowres_wide lowres_wide_intrinsics ultrawide ultrawide_intrinsics vga_wide vga_wide_intrinsics
> ```

Thanks for the comment.
it Is working now.

**Comment by PeterZheFu** [comment]
Thank you all for your interest in our dataset and highlighting the issue. I will close the issue for now. Please feel free to re-open it if you have any questions.
