### ISSUE TITLE
The upsampling  dataset

### ISSUE THREAD

**Issue by MemoryNode** [apple/ARKitScenes#5]
Hi, @PeterZheFu

i download the upsampling dataset, there are 4 types assets,  confidence,  lowres_depth,  highres_depth and wide_rgb.

The highres_depth is the ground-truth or the result of upsampling network(MSG/MSPF) ?

If i want to train the network , how to generate the metadata.csv file ?  what does this file mean ?

**Comment by PeterZheFu** [comment]
Hi @MemoryNode,
    Thanks for your interest and questions~
    For the first question, highres_depth is the ground-truth.

**Comment by PeterZheFu** [comment]
For the second question, metadata.csv is a summary file for all available assets. The purpose of it is for users to know what files are available without downloading the actual files, as some of the files are huge in size.

**Comment by PeterZheFu** [comment]
Closing this issue for now. Feel free to re-open it if you have any further questions~
