### ISSUE TITLE
Rectification

### ISSUE THREAD

**Issue by mahtabbigverdi** [apple/ARKitScenes#51]
https://github.com/apple/ARKitScenes/blob/e2e975128a0a9695ea56fa215fe76b4295241538/threedod/benchmark_scripts/rectify_im.py#L63

  I tested the code for video id 47333462 and it returned "3" which means a 90-degree rotation, however, the images look good and don't need any rectification.

**Comment by afshindn** [comment]
@mahtabbigverdi I hope the answer above fixed your issue. Please let us know if there is any other concerns.

**Comment by mahtabbigverdi** [comment]
I picked the most frequent index, but for example for video 41048071.mov, all indices for all frames are 1, which means 90 degree counterclockwise rotations but the actual video doesn't need any rectifications

**Comment by Levintsky** [comment]
I checked the video 41048071, the image should be counterclockwise rotated. For example, the one named 41048071_4518.913.png. For images taken with camera facing down on the ground or directly to the floor, our algorithm does not handle those cases.
![41048071_4518 913](https://user-images.githubusercontent.com/50941287/221702573-026feb49-1e61-4602-8fdb-28f521ed1e31.png)
