### ISSUE TITLE
Camera coordinates convention

### ISSUE THREAD

**Issue by dcaffo98** [apple/ARKitScenes#59]
Hi, thank you for releasing this dataset.
I'd like to know the coordinate convention used to store the camera trajectory rotations. What are the directions corresponding to the X, Y, and Z rotation axes? Can you provide this information in the docs, i.e. as you did for the [Hypersim](https://github.com/apple/ml-hypersim#coordinate-conventions) dataset?

**Comment by PeterZheFu** [comment]
Hi @dcaffo98,
   Thanks for your question. For parsing the camera trajectory rotations, we have a sample function here https://github.com/apple/ARKitScenes/blob/main/threedod/benchmark_scripts/utils/tenFpsDataLoader.py#L36C15-L36C15
   Hope this would be helpful. Please let me know if you have further questions.

**Comment by PeterZheFu** [comment]
Closing the issue. Please feel free to re-open it if you have any questions.
