### ISSUE TITLE
Mesh and high-resolution point-clouds in the dataset

### ISSUE THREAD

**Issue by penghaohsu0222** [apple/ARKitScenes#60]
Thank you for the useful dataset!
I'm wondering about the source of the mesh data in the 3dod dataset. Were FARO LiDAR scanners used to create these detailed meshes? Also, do these meshes relate to the high-resolution point clouds in the raw data? Your clarification would be appreciated.

**Comment by penghaohsu0222** [comment]
@arik1089 @afshindn 
I would greatly appreciate your help in understanding how to generate the mesh.
Thank you very much in advance for your time and assistance. Your help would be greatly appreciated.

**Comment by dgriffiths3** [comment]
The mesh is generated from back projected ARKit depth maps (from iPad Pro). They are independent of the Faro point clouds.

**Comment by AIBluefisher** [comment]
> The mesh is generated from back projected ARKit depth maps (from iPad Pro). They are independent of the Faro point clouds. Please feel free to re-open if you have any additional questions.

Hi @dgriffiths3 ,

Could you provide more details here in how you generate the meshes? e.g., (1) The camera poses used for mesh generation are obtained from ARKit or from the ground-truth poses aligned with the laser scan? (2) After depth projections, how do you fuse the depth into meshes (using TSDF or other methods)?
