### ISSUE TITLE
ARKit Scene Understanding classification data

### ISSUE THREAD

**Issue by littlejohntj** [apple/ARKitScenes#67]
As an iOS developer, when I build apps with ARKit I am able to access a classification on each face when I use ARKit's scene understanding capabilities. Is this data available as part of this dataset?

**Comment by littlejohntj** [comment]
i see now that the data collection has the mesh overlay which make me believe there was access to the classification data. was this collected? if so, what data set do i need to download to find it?

**Comment by PeterZheFu** [comment]
Hi @littlejohntj , 
    Thanks for your question and interest in our dataset. I am afraid that we do not have the above mentioned data in this dataset.
