### ISSUE TITLE
Question about .traj

### ISSUE THREAD

**Issue by tau-yihouxiang** [apple/ARKitScenes#8]
Thank you for the large-scale indoor dataset. I noticed that only 1/6 images have pose parameters in 'lowres_wide.traj' file. Are there more posed images?  Does there exist 'vga_wide.traj' files?

**Comment by tau-yihouxiang** [comment]
I found another issue: some .traj files cannot be downloaded:
'''
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5HGKA02B953JGBRQ</RequestId><HostId>idjfXV4Hjer8vAWdVZshlVJoObDuFZ9kqyAFANZ4riFU3Xnrgq17kgEKwFtfr66op4NhpPrmQTo=</HostId></Error>
'''
For example, 'ARKitScenes/raw/raw/Training/48018149/lowres_wide.traj' and 'ARKitScenes/raw/raw/Training/47430089/lowres_wide.traj'

**Comment by PeterZheFu** [comment]
Hi @tau-yihouxiang,
    Thanks for your interest and reaching out. Sorry for my belated reply.
    The .traj poses are run at a different fps, i.e. 10 fps whilst the lowres can be at 60 fps. Thus only 1/6 images have poses. Nevertheless, if needed you can probably interpolate to get the intermediate poses.

**Comment by PeterZheFu** [comment]
Hi @tau-yihouxiang,
    Thanks raising the asset downloading issue. Let me check on it.

**Comment by PeterZheFu** [comment]
Hi @tau-yihouxiang,
   Sorry for my belated reply. The .traj files are missing/corrupted because this particular video(s) is used in depth_upsampling but not in 3dod (where we use camera poses). Therefore the camera poses are not included. 
   Closing the issue for now. Please feel free to re-open it if you have further questions.

**Comment by PeterZheFu** [comment]
That being said, we are adapting the download script to throw a message in case it happens. Thank you for raising this up~

**Comment by PeterZheFu** [comment]
re-opening this issue till it is fully resolved
